# Generated by Django 4.2.5 on 2023-10-04 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost_price', models.FloatField(default=0.0)),
                ('selling_price', models.FloatField(default=0.0)),
                ('sale_tax', models.BooleanField(default=False)),
                ('stock', models.FloatField(default=0)),
                ('expiry_date', models.DateField(blank=True)),
                ('batch_number', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item',
                'indexes': [models.Index(fields=['id', 'item_name'], name='item_id_c0baf3_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('item_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost_price', models.FloatField(default=0.0)),
                ('selling_price', models.FloatField(default=0.0)),
                ('sale_tax', models.BooleanField(default=False)),
                ('stock', models.FloatField(default=0)),
                ('expiry_date', models.DateField(blank=True)),
                ('batch_number', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical item',
                'verbose_name_plural': 'historical items',
                'db_table': 'item_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
